version: '3.8'

services:
  app:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
      - 3000:3000
    # env_file:
    #   - ./.env.dev
